FROM ubuntu

RUN apt update && apt install g++ -y && apt install python2.7 -y && apt install python3.7 -y && apt install openjdk-8-jdk -y
RUN apt install haskell-platform -y
RUN apt-get install curl build-essential m4 zlib1g-dev libssl-dev ocaml ocaml-native-compilers opam -y
RUN apt install rustc -y